PATCH https://wikied-api.vercel.app/6-6/profiles/51cf7834-417c-4002-80f4-499de01ec80e
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTY5LCJ0ZWFtSWQiOiI2LTYiLCJzY29wZSI6ImFjY2VzcyIsImlhdCI6MTcxOTgxMTI1OSwiZXhwIjoxNzE5ODEzMDU5LCJpc3MiOiJzcC13aWtpZWQifQ.U7hGLq3Zh9BO1NrD_vYTGn_6tg9VvXgZqgcjXP8bMao
Content-Type: application/json

{
  "nationality": "테스트",
  "family": "엄마아빠",
  "bloodType": "b",
  "nickname": "별명임",
  "birthday": "2022-10-11",
  "sns": "snsexample",
  "job": "프론트엔드 개발자",
  "mbti": "intp",
  "city": "서울"
}

### 회원가입
POST https://wikied-api.vercel.app/6-6/auth/signUp
Content-Type: application/json

{
    "name": "signUpTest",
    "email": "signUpTest@email.com",
    "password": "signUpTest",
    "passwordConfirmation":"signUpTest"
}

### 로그인
POST https://wikied-api.vercel.app/6-6/auth/signIn
Content-Type: application/json

{
    "email": "signUpTest@email.com",
    "password": "signUpTest"
}

### 로그인
POST https://wikied-api.vercel.app/6-6/auth/signIn
Content-Type: application/json

{
    "email": "stophyun@email.com",
    "password": "stophyun123"
}

### 토큰 갱신
POST https://wikied-api.vercel.app/6-6/auth/refresh-token
Content-Type: application/json

{"refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTc1LCJ0ZWFtSWQiOiI2LTYiLCJzY29wZSI6InJlZnJlc2giLCJpYXQiOjE3MTk1ODAwOTEsImV4cCI6MTcyMDE4NDg5MSwiaXNzIjoic3Atd2lraWVkIn0.Dyj16x1oihm08Lq59fzU5v5jyV8Lqv1BMTEaoLhe_Ng"}

### 로그인
POST https://wikied-api.vercel.app/6-6/auth/signIn
Content-Type: application/json

{
    "email": "test1234@email.com",
    "password": "test1234"
}
